simulation_properties:

  - name: time_step
    value: 1.0 # seconds

  - name: max_simulation_time
    value: 12000.0 # seconds

  - name: log_interval_steps
    value: 10.0 # seconds

initial_conditions:

    # I will later add the option to specify orbital parameters instead of state directly  

  - name: semi-major_axis
    value: 6968000.0 # m
    deviation: 10000 # m 

  - name: eccentricity
    value: 0.000
    deviation: 0.000

  - name: inclination
    value: 98.0 # degrees
    deviation: 0.5 # degrees

  - name: raan
    value: 171 # degrees
    deviation: 20 # degrees

  - name: argument_of_perigee
    value: 63 # degrees
    deviation: 10 # degrees

  - name: true_anomaly
    value: 0.0 # degrees
    deviaation: 10 # degrees

  - name : attitude
    value: [1.0, 0.0, 0.0, 0.0] # quaternion (w x y z)

  - name: attitude_rate
    value: [-2.154434690031884, 2.154434690031884, -2.154434690031884] # rad/s (10 rpm)


physical_properties:

  - name: main_body
    dimensions: # Dictionary convention: body-frame extents in meters along x, y, z
      x: 0.1 # m
      y: 0.1 # m
      z: 0.1 # m
    faces:
      face_dimensions: # m
        x+: [0.1, 0.1] 
        x-: [0.1, 0.1] 
        y+: [0.1, 0.1] 
        y-: [0.1, 0.1] 
        z+: [0.1, 0.1] 
        z-: [0.1, 0.1] 
      face_normals: # unit normal
        x+: [1.0, 0.0, 0.0]  
        x-: [-1.0, 0.0, 0.0]
        y+: [0.0, 1.0, 0.0]
        y-: [0.0, -1.0, 0.0]
        z+: [0.0, 0.0, 1.0]
        z-: [0.0, 0.0, -1.0]
    geometric_center: # Dictionary convention: body-frame component center in meters relative to the spacecraft origin
      x: 0.0 # m
      y: 0.0 # m
      z: 0.0 # m
    mass: 1.15 # kg

  - name: x+_deployable
    dimensions: # Dictionary convention: body-frame extents in meters along x, y, z
      x: 0.1 # m
      y: 0.082 # m
      z: 0.00385 # m
    faces:
      face_dimensions: # m
        z+: [0.1, 0.082]
        z-: [0.1, 0.082]
      face_normals: 
        z+: [1.0, 0.0, 0.0]
        z-: [-1.0, 0.0, 0.0]
    geometric_center:
      x: 0.1 # m
      y: 0.0 # m
      z: 0.498075 # m
    normal_vector: # Unit body-frame normal for the panel
      x: 1.0
      y: 0.0
      z: 0.0
    mass: 0.03507 # kg

  - name: x-_deployable
    dimensions: # Dictionary convention: body-frame extents in meters along x, y, z
      x: 0.1 # m
      y: 0.082 # m
      z: 0.00385 # m
    faces:
      face_dimensions: # m
        z+: [0.1, 0.082]
        z-: [0.1, 0.082]
      face_normals: # unit normal
        z+: [1.0, 0.0, 0.0]
        z-: [-1.0, 0.0, 0.0]
    geometric_center:
      x: -0.1 # m
      y: 0.0 # m
      z: 0.498075 # m
    normal_vector: # Unit body-frame normal for the panel
      x: -1.0
      y: 0.0
      z: 0.0
    mass: 0.03507 # kg

  - name: y+_deployable
    dimensions: # Dictionary convention: body-frame extents in meters along x, y, z
      x: 0.082 # m
      y: 0.1 # m
      z: 0.00385 # m
    faces:
      face_dimensions: # m
        z+: [0.082, 0.1]
        z-: [0.082, 0.1]
      face_normals: # unit normal
        z+: [0.0, 1.0, 0.0]
        z-: [0.0, -1.0, 0.0]
    geometric_center:
      x: 0.0 # m
      y: 0.1 # m
      z: 0.498075 # m
    normal_vector: # Unit body-frame normal for the panel
      x: 0.0
      y: 1.0
      z: 0.0
    mass: 0.03507 # kg

  - name: y-_deployable
    dimensions: # Dictionary convention: body-frame extents in meters along x, y, z
      x: 0.082 # m
      y: 0.1 # m
      z: 0.00385 # m
    faces:
      face_dimensions: # m
        z+: [0.082, 0.1]
        z-: [0.082, 0.1]
      face_normals: # unit normal
        z+: [0.0, 1.0, 0.0]
        z-: [0.0, -1.0, 0.0]
    geometric_center:
      x: 0.0 # m
      y: -0.1 # m
      z: 0.498075 # m
    normal_vector: # Unit body-frame normal for the panel
      x: 0.0
      y: -1.0
      z: 0.0
    mass: 0.03507 # kg


dynamics_properties:

 - name: state_size
   value: 14 # position, velocity, quaternion, quaternion derivative


integration_properties:
 
  # For future use in the potential of using a different integration scheme
 - name: integration_method
   value: rk4